const services = [
  {
    slug: "local-seo",
    icon: "🔍",
    title: "Local SEO",
    subtitle: "Dominate Google Maps in Dhaka & Across Bangladesh",
    qa: "Local SEO helps your business appear in Google Maps and local search results when customers near you search for your services. It involves optimizing your Google Business Profile, building local citations on Bangladeshi directories, and targeting location-based keywords like 'SEO near me in Dhaka'. This is essential for brick-and-mortar businesses in Dhaka, Chittagong, Sylhet, and across Bangladesh who want more foot traffic and local calls.",
    shortDesc: "Rank on Google Maps across Dhaka, Mirpur, Gulshan, Banani, Uttara and more. GBP optimization, BD Yellow Pages citations, and near-me SEO for Bangladesh.",
    desc: "Get your business found by customers searching near you across Bangladesh. I optimise your Google Business Profile (GBP), build local citations on Bangladeshi directories like BD Yellow Pages and Bdshop, and target location-based keywords so you appear in the local pack and Google Maps. My Local SEO service is specifically designed for Dhaka, Mirpur, Gulshan, Banani, Uttara, Dhanmondi, Chittagong, Sylhet, and all major cities in Bangladesh. I help businesses rank for 'near me' searches, Google Maps queries, and bilingual Bengali + English keywords.",
    features: [
      "Google Business Profile optimization for Bangladesh locations (Dhaka, Chittagong, Sylhet)",
      "Local citation building on Bangladeshi directories (BD Yellow Pages, Bdshop, BdTradeInfo)",
      "Near-me keyword targeting ('SEO near me', 'best service in Dhaka', 'restaurant near Gulshan')",
      "Google Maps ranking strategy for local businesses",
      "Local content strategy with Bangla + English keywords",
      "Review generation & reputation management on Google",
      "Google Business Profile verified setup & onboarding",
    ],
    benefits: [
      "Appear on Google Maps for local searches in Dhaka & beyond",
      "Get more calls, directions, and website visits from local customers",
      "Outrank competitors in your area with targeted local SEO",
      "Build trust with authentic Google reviews and ratings",
    ],
    process: [
      "Google Business Profile audit & optimization",
      "Local keyword research (Bengali + English)",
      "Citation building on top BD directories like Yellow Pages",
      "Content optimization for local search intent",
      "Monthly ranking reports & optimization",
    ],
    faq: [
      { question: "How long does local SEO take to show results in Dhaka?", answer: "Most clients in Dhaka see initial improvements in 4–6 weeks, with significant ranking improvements in 3–6 months. Local SEO results depend on competition, your current online presence, and how quickly we can optimize your Google Business Profile and build local citations on BD Yellow Pages and other Bangladeshi directories." },
      { question: "Do you offer local SEO for Chittagong and Sylhet?", answer: "Yes, I offer local SEO services for all major cities in Bangladesh including Chittagong, Sylhet, Dhaka, Mirpur, Gulshan, Banani, Uttara, Dhanmondi, and Khulna. My strategies are tailored to each city's local search landscape and bilingual Bengali + English search behavior." },
      { question: "What is Google Business Profile optimization for Bangladesh businesses?", answer: "GBP optimization involves verifying and fully optimizing your Google Business Profile with accurate NAP (Name, Address, Phone), selecting relevant categories, adding photos of your Bangladesh location, collecting Google reviews from local customers, and posting regular updates to improve local pack rankings in Dhaka and across Bangladesh." },
    ],
  },
  {
    slug: "on-page-seo",
    icon: "📄",
    title: "On-Page SEO",
    subtitle: "Perfect Every Page for Search & Users",
    qa: "On-Page SEO is the practice of optimizing individual web pages to rank higher on Google by improving content, HTML tags, and site structure. It includes optimizing title tags, meta descriptions, headers, internal links, and images with relevant keywords. For Bangladeshi businesses, this means targeting both Bengali and English search queries to capture the widest possible audience in Dhaka, Chittagong, and Sylhet.",
    shortDesc: "Keyword-optimized content, meta tags, header structure, internal linking, and schema markup crafted for Bangladesh search behavior including Dhaka, Chittagong, and Sylhet audiences.",
    desc: "I optimise every page on your site — from title tags and meta descriptions to header structure and internal linking — so Google understands your content and ranks it higher. My On-Page SEO service follows Google's E-E-A-T guidelines and targets Bangladesh-specific search patterns including Bengali and English keyword queries. I implement schema markup for LocalBusiness, Article, FAQ, and Product entities, and optimize for Google NLP-based ranking factors. This service is ideal for businesses in Dhaka, Chittagong, Sylhet, and all across Bangladesh.",
    features: [
      "Title tag & meta description optimisation for CTR in Bangladesh market",
      "Header (H1-H3) structure with targeted Bengali + English keywords",
      "Keyword-optimised content following Google E-E-A-T guidelines",
      "Internal linking architecture for better crawlability",
      "Image alt text & Schema.org markup implementation (LocalBusiness, Article, FAQ)",
      "Content gap analysis & topical relevance improvement",
      "NLP-optimized content structuring for semantic search",
    ],
    benefits: [
      "Higher rankings for your target keywords in Bangladesh",
      "Better click-through rates with optimized meta descriptions",
      "Improved user engagement with structured content",
      "Comprehensive schema markup for rich snippets",
    ],
    process: [
      "Full page content & structure audit",
      "Keyword mapping for each page",
      "Title, meta, header optimization",
      "Internal link restructuring",
      "Schema markup implementation",
      "Performance tracking & refinement",
    ],
    faq: [
      { question: "What is included in on-page SEO for Bangladesh businesses?", answer: "My on-page SEO service includes title tag and meta description optimization, header structure improvements, keyword-optimized content for both Bengali and English queries, internal linking architecture, image alt text, and LocalBusiness schema markup implementation. All work follows Google's E-E-A-T guidelines tailored for the Dhaka and Bangladesh market." },
      { question: "How do you optimize for both Bengali and English keywords?", answer: "I conduct comprehensive keyword research using Google Keyword Planner, Ahrefs, and local Bangladesh search data to find high-intent keywords in both Bengali and English. Content is structured to capture bilingual search queries, helping businesses in Dhaka, Chittagong, and Sylhet reach the widest possible audience." },
      { question: "What schema markup do you implement for Bangladeshi businesses?", answer: "I implement JSON-LD structured data for LocalBusiness, Organization, Article, FAQ, BreadcrumbList, and Product schema types depending on your site's content. This helps Google understand your business entity and can unlock rich snippets in search results for better click-through rates." },
    ],
  },
  {
    slug: "link-building",
    icon: "🔗",
    title: "Link Building",
    subtitle: "Build Authority That Ranks",
    qa: "Link Building is the process of acquiring high-quality backlinks from other websites to yours, which signals to Google that your site is authoritative and trustworthy. I use ethical, white-hat techniques like guest posting on Bangladeshi news sites and local directory submissions. Quality backlinks from BD Yellow Pages, Dhaka Tribune, and industry-specific sites help your website rank higher on Google search results.",
    shortDesc: "Quality backlinks from Bangladeshi and international directories like BD Yellow Pages, guest posts on Bangladeshi news sites, and niche-relevant websites that drive real authority gains for Dhaka businesses.",
    desc: "Quality backlinks from Bangladeshi and international websites. I use ethical, white-hat techniques to build your site's authority and drive referral traffic. My link building strategy focuses on acquiring high-authority backlinks from Bangladesh's top business directories including BD Yellow Pages and BdTradeInfo, local news sites like The Daily Star and Dhaka Tribune, and industry-relevant platforms. I also build links from Facebook, YouTube, and other social platforms where Bangladeshi audiences engage. Every strategy complies with Google's Webmaster Guidelines.",
    features: [
      "Guest posting on high-authority Bangladeshi websites and news sites",
      "Local directory submissions on BD Yellow Pages, BdTradeInfo, and Bangladesh business directories",
      "Niche-relevant backlinks from industry-specific Bangladeshi sources",
      "Broken link building for quick authority gains",
      "Competitor backlink analysis & gap identification for Bangladesh market",
      "Authority building strategy with white-hat methods",
      "Digital PR for Bangladeshi news coverage and editorial backlinks",
    ],
    benefits: [
      "Boost your site's Domain Authority and search rankings",
      "Get referral traffic from high-quality Bangladeshi websites",
      "Build sustainable backlink profile with white-hat techniques",
      "Outrank competitors with superior link authority",
    ],
    process: [
      "Backlink audit & competitor analysis",
      "Prospect identification (BD & international)",
      "Outreach & relationship building",
      "Content creation for guest posts",
      "Backlink monitoring & disavow management",
    ],
    faq: [
      { question: "What types of backlinks do you build for Bangladeshi businesses?", answer: "I build high-quality backlinks through guest posting on authoritative Bangladeshi websites like The Daily Star and Dhaka Tribune, local directory submissions on BD Yellow Pages and BdTradeInfo, niche-relevant editorial links, broken link building, and digital PR campaigns targeting Bangladeshi news outlets." },
      { question: "Are your link building methods white-hat and Google-compliant?", answer: "Absolutely. I only use ethical, white-hat link building techniques that comply with Google's Webmaster Guidelines. No PBNs, paid links, or spammy tactics that could get your site penalized. Every backlink is earned through genuine value creation and relationship building with Bangladeshi publishers." },
      { question: "How do you acquire backlinks from Bangladeshi websites?", answer: "I specialize in acquiring backlinks from high-authority Bangladeshi domains including news sites (Daily Star, Dhaka Tribune), business directories (BD Yellow Pages, BdTradeInfo), educational institutions (.edu.bd domains), and industry-specific platforms relevant to your niche in Dhaka, Chittagong, or Sylhet." },
    ],
  },
  {
    slug: "technical-seo",
    icon: "⚙️",
    title: "Technical SEO",
    subtitle: "Fix the Foundation. Improve Rankings.",
    qa: "Technical SEO involves optimizing your website's infrastructure so search engines like Google can effectively crawl, index, and rank your pages. It covers site speed optimization, Core Web Vitals improvement, mobile usability fixes, structured data implementation, and crawl budget management. For Bangladesh's mobile-first audience, good technical SEO is the foundation upon which all other SEO efforts are built.",
    shortDesc: "Core Web Vitals, site speed, mobile-first indexing, crawl budget fixes, and JSON-LD structured data for better Google rankings in Bangladesh.",
    desc: "I audit and fix technical issues holding your site back — slow speed, crawl errors, mobile issues, and Core Web Vitals — so search engines like Google can easily find and rank your pages. Technical SEO is the foundation upon which all other SEO efforts are built. I optimize for Google's PageSpeed Insights, Lighthouse, and Google Search Console. My service ensures your website performs well on mobile devices used across Dhaka, Chittagong, Sylhet, and all of Bangladesh. I implement JSON-LD structured data for Schema.org entity types including LocalBusiness, Organization, and Article.",
    features: [
      "Core Web Vitals optimisation (LCP, FID/INP, CLS) for Google ranking factors",
      "Site speed & performance audit with actionable fixes for Bangladesh hosting",
      "Mobile-first indexing check & optimization for Bangladesh's mobile users",
      "Crawl budget optimisation for better indexation on Google",
      "Structured data / Schema markup (JSON-LD) for LocalBusiness, Organization, Article",
      "Sitemap & robots.txt management for optimal crawling",
      "Google Search Console setup, monitoring & issue resolution",
    ],
    benefits: [
      "Faster loading pages that keep visitors engaged",
      "Better mobile experience for Bangladesh's mobile-first users",
      "Improved crawlability leading to more indexed pages",
      "Rich snippets in search results with proper schema",
    ],
    process: [
      "Comprehensive technical audit (30+ checkpoints)",
      "Core Web Vitals analysis & optimization",
      "Mobile usability fixes",
      "Crawl & indexation optimization",
      "Schema markup deployment",
      "Monthly technical monitoring",
    ],
    faq: [
      { question: "What is Core Web Vitals and why does it matter for Bangladeshi websites?", answer: "Core Web Vitals are Google's set of metrics measuring real-world user experience — loading speed (LCP), interactivity (INP), and visual stability (CLS). They are direct ranking factors that impact your search positions. For Bangladeshi websites with mobile-first audiences, optimizing Core Web Vitals is critical for ranking on Google." },
      { question: "How do you fix site speed issues for Bangladesh-hosted websites?", answer: "I use Google PageSpeed Insights and Lighthouse to diagnose speed bottlenecks, then implement fixes including image optimization to WebP format, code minification, browser caching, CDN integration (Cloudflare), and server response time improvements. These optimizations are especially important for users accessing your site from Dhaka on mobile 4G/5G networks." },
      { question: "How do you implement structured data for Bangladeshi businesses?", answer: "I implement JSON-LD structured data markup for various schema types including LocalBusiness (essential for Dhaka, Chittagong, Sylhet businesses), Organization, Article, Product, FAQ, BreadcrumbList, and Review — all following Schema.org standards to help Google understand your entity and unlock rich search results." },
    ],
  },
  {
    slug: "geo-ai-search",
    icon: "🤖",
    title: "GEO & AI Search",
    subtitle: "Get Found in ChatGPT, Gemini & AI Overviews",
    qa: "GEO (Generative Engine Optimization) is the practice of optimizing your content to be cited by AI-powered search engines like ChatGPT, Google AI Overviews, Gemini, and Perplexity. It focuses on entity-based content, structured data, and authoritative citations that AI systems trust. GEO prepares your Bangladesh business for the future of AI-powered search discovery and ensures you appear in AI-generated answers.",
    shortDesc: "Optimize for ChatGPT, Gemini, Perplexity, and Google AI Overviews. Entity-first SEO built for the AI-powered search era targeting Dhaka and Bangladesh businesses.",
    desc: "Optimise your content for the AI-powered search era. I structure your site so AI systems — Google AI Overviews, ChatGPT by OpenAI, Gemini by Google, Perplexity, and Claude — can accurately extract and cite your business. GEO (Generative Engine Optimization) is the future of search, and I prepare your Bangladesh business for it. I implement entity-first content structures, semantic topical clusters, and E-E-A-T signals that AI search engines trust. This service is essential for Dhaka businesses looking to appear in AI-generated answers.",
    features: [
      "Entity-first content structure for AI understanding (Google, ChatGPT, Gemini)",
      "AI-friendly FAQ/QA optimisation for featured snippets and AI citations",
      "Semantic topical clustering for authority building in Bangladesh niches",
      "Authority signal building for Google E-E-A-T compliance",
      "Featured snippet targeting & optimization for AI extraction",
      "Generative Engine readiness for ChatGPT, Gemini, Perplexity & Claude",
      "Entity optimization for Google Knowledge Graph inclusion",
    ],
    benefits: [
      "Get cited in Google AI Overviews for your target queries",
      "Appear in ChatGPT, Gemini and Perplexity responses",
      "Future-proof your SEO for the AI search era",
      "Build entity-based authority that lasts",
    ],
    process: [
      "AI search readiness audit",
      "Entity extraction & content restructuring",
      "FAQ & Q&A content optimization for AI extraction",
      "Topical authority cluster development",
      "E-E-A-T signal enhancement",
      "Monthly GEO performance monitoring",
    ],
    faq: [
      { question: "What is GEO (Generative Engine Optimization) and why does it matter for Bangladeshi businesses?", answer: "GEO is the practice of optimizing your content to be accurately cited and referenced by AI-powered search engines like Google AI Overviews, ChatGPT, Gemini, Perplexity, and Claude. It focuses on entity-based content and authoritative source building. For Bangladeshi businesses, GEO represents an opportunity to get featured in AI answers before competitors catch up." },
      { question: "How do I get my Dhaka business in ChatGPT and Gemini responses?", answer: "To appear in ChatGPT and Gemini responses, your website needs strong topical authority, clear entity signals (Organization and LocalBusiness schema), well-structured FAQ content, and citations from authoritative sources. I implement entity-first SEO strategies to achieve this for businesses in Dhaka, Chittagong, Sylhet, and across Bangladesh." },
      { question: "Do you optimize for Google AI Overviews (formerly SGE)?", answer: "Yes, I optimize your content to be featured in Google AI Overviews by implementing clear entity definitions, authoritative citations, FAQ/QA structures, and comprehensive topical coverage. This is especially valuable for Bangladeshi businesses wanting to dominate AI-generated search results." },
    ],
  },
  {
    slug: "ecommerce-seo",
    icon: "🛒",
    title: "E-commerce SEO",
    subtitle: "Sell More With Organic Search",
    qa: "E-commerce SEO is the process of optimizing your online store — whether on Daraz, Shopify, or WooCommerce — to rank higher in search results and attract more buyers. It includes product page optimization, category structuring, fixing duplicate content from faceted navigation, and implementing product schema markup. For Bangladeshi e-commerce businesses, this means more organic traffic and sales from Google.",
    shortDesc: "Shopify, Daraz, WooCommerce SEO. Product page optimization, category restructuring, and conversion-focused search for Bangladeshi online retailers.",
    desc: "From Daraz sellers to Shopify and WooCommerce stores, I optimise product pages, category structure, and technical setup so your products rank higher and convert better. My E-commerce SEO service is tailored for Bangladeshi online retailers selling on local platforms like Daraz Bangladesh and international platforms like Shopify. I handle product schema markup, faceted navigation issues, duplicate content from product variations, and optimize for Google Shopping. Whether you're in Dhaka, Chittagong, or Sylhet, I help your e-commerce store capture organic search traffic.",
    features: [
      "Product page optimisation for search & conversions on Google",
      "Category structure & siloing for better topical authority",
      "Shopify/WooCommerce/Daraz SEO best practices for Bangladesh",
      "Review schema & rich snippets for product pages",
      "E-commerce site speed optimization for mobile users",
      "Conversion-focused SEO strategy for BD e-commerce",
      "Daraz seller page optimization for Daraz search + Google visibility",
    ],
    benefits: [
      "Rank product pages for high-intent purchase keywords",
      "Fix crawl budget, duplicate content & faceted navigation",
      "Increase organic traffic to category & product pages",
      "Boost e-commerce conversion rate with SEO-optimized content",
    ],
    process: [
      "E-commerce site audit (technical + content)",
      "Product & category keyword mapping",
      "On-page optimization for product pages",
      "Category structure & internal linking overhaul",
      "Schema markup (Product, Review, Breadcrumb)",
      "Monthly performance reporting & optimization",
    ],
    faq: [
      { question: "Do you optimize Daraz seller pages for Bangladeshi sellers?", answer: "Yes, I optimize Daraz seller pages for better visibility within Daraz's search and for Google. I focus on product titles with high-volume keywords, detailed descriptions in both English and Bengali, high-quality images, category placement, and review signals to boost rankings. This helps Daraz sellers in Dhaka, Chittagong, and Sylhet get more sales." },
      { question: "Can you work with Shopify stores targeting Bangladesh customers?", answer: "Yes, I specialize in Shopify SEO including collection page optimization, meta fields management, blog content strategy, URL structure fixes, and Shopify-specific technical SEO improvements. I help Bangladeshi Shopify stores rank for local and international keywords on Google." },
      { question: "How do you handle duplicate content in e-commerce sites for Bangladesh?", answer: "I address duplicate content issues common in e-commerce sites — product variations, faceted navigation, and manufacturer descriptions — using canonical tags, parameter handling, and unique product descriptions. This is crucial for Daraz sellers and Shopify stores in Dhaka to avoid Google ranking penalties." },
    ],
  },
  {
    slug: "semantic-seo",
    icon: "🧠",
    title: "Semantic SEO",
    subtitle: "Build Topical Authority That Search Engines Love",
    qa: "Semantic SEO goes beyond individual keywords to structure your website around topics, entities, and user intent. It uses topic clusters, entity linking via Schema.org, and co-occurrence patterns to build deep topical authority that Google understands. Semantic SEO naturally prepares your site for both traditional search rankings and AI-powered search engines like ChatGPT and Gemini.",
    shortDesc: "Entity-based SEO, topic clusters, semantic relevance optimization. Rank for topic families — not just keywords — with Bangladesh-focused semantic SEO for Dhaka, Chittagong, and Sylhet markets.",
    desc: "I structure your website around topics and entities — not just keywords — so search engines like Google understand your expertise at a deeper level. Semantic SEO uses topic clusters, entity linking via Schema.org, and co-occurrence patterns to build topical authority. This is the most advanced approach for dominating competitive niches in Bangladesh and beyond. I optimize for entity recognition by Google Knowledge Graph, implement LocalBusiness, Person, and Service schema, and build entity relationships that improve your chances of appearing in rich results and AI-powered search.",
    features: [
      "Topic cluster & pillar page strategy for authority building",
      "Entity extraction & semantic relevance optimization for Google NLP",
      "Co-occurrence & LSI keyword targeting for deep relevance in Bangladesh",
      "Internal linking based on semantic relationships and entity connections",
      "Schema.org markup for entities (Person, LocalBusiness, Organization, Service)",
      "Knowledge Graph optimization & entity disambiguation for Google",
      "Semantic entity relationships for AI search readiness (ChatGPT, Gemini)",
    ],
    benefits: [
      "Own topic families — not just isolated keywords",
      "Build true topical authority Google rewards",
      "Future-proof your SEO for semantic & AI search",
      "Get featured in Knowledge Panels & rich results",
    ],
    process: [
      "Semantic gap analysis & entity audit",
      "Topic cluster architecture design",
      "Pillar & cluster content development",
      "Entity linking & co-occurrence optimization",
      "Schema.org entity markup implementation",
      "Monthly semantic authority monitoring",
    ],
    faq: [
      { question: "What is semantic SEO and how is it different from traditional SEO for Bangladesh?", answer: "Semantic SEO goes beyond keywords to optimize for topics, entities, and user intent. It uses topic clusters, entity linking via Schema.org, and co-occurrence patterns to build topical authority that Google rewards with higher rankings. For Bangladeshi businesses, semantic SEO means structuring content around entities like 'Dhaka', 'Google Business Profile', 'Daraz', and 'BD Yellow Pages' in ways that search engines and AI understand." },
      { question: "How does entity SEO help my website rank on Google?", answer: "Entity SEO helps Google understand the real-world entities your business is associated with — people, places, services, and concepts. This improves your chances of appearing in Google Knowledge Graphs, rich snippets, and AI search results. For example, linking your Dhaka business to LocalBusiness schema helps Google Maps rankings." },
      { question: "Can semantic SEO help with ChatGPT and Gemini optimization?", answer: "Absolutely. Semantic SEO's focus on entities, relationships, and topical authority aligns perfectly with how AI search engines like ChatGPT and Gemini understand and cite content. It naturally prepares your site for GEO (Generative Engine Optimization) and AI-powered search." },
    ],
  },
];

export default services;
