const services = [
  {
    slug: "local-seo",
    icon: "🔍",
    title: "Local SEO",
    subtitle: "Dominate Google Maps in Dhaka & Across Bangladesh",
    shortDesc: "Rank your business on Google Maps across Dhaka, Chittagong, Sylhet and beyond. GBP optimization, local citations, near-me SEO for Bangladeshi audiences.",
    desc: "Get your business found by customers searching near you. I optimise your Google Business Profile, build local citations on Bangladeshi directories, and target location-based keywords so you appear in the local pack and Google Maps. My Local SEO service is specifically designed for Dhaka, Chittagong, Sylhet, and all major cities in Bangladesh.",
    features: [
      "Google Business Profile optimization for Bangladesh locations",
      "Local citation building on Bangladeshi directories (Bdshop, Yellow Pages BD)",
      "Near-me keyword targeting ('SEO near me', 'best service in Dhaka')",
      "Google Maps ranking strategy for local businesses",
      "Local content strategy with Bangla + English keywords",
      "Review generation & reputation management",
    ],
    benefits: [
      "Appear on Google Maps for local searches in Dhaka & beyond",
      "Get more calls, directions, and website visits from local customers",
      "Outrank competitors in your area with targeted local SEO",
      "Build trust with authentic Google reviews and ratings",
    ],
    process: [
      "Google Business Profile audit & optimization",
      "Local keyword research (Bengali + English)",
      "Citation building on top BD directories",
      "Content optimization for local search intent",
      "Monthly ranking reports & optimization",
    ],
  },
  {
    slug: "on-page-seo",
    icon: "📄",
    title: "On-Page SEO",
    subtitle: "Perfect Every Page for Search & Users",
    shortDesc: "Keyword-optimized content, meta tags, header structure, internal linking, and schema markup crafted for Bangladesh search behavior.",
    desc: "I optimise every page on your site — from title tags and meta descriptions to header structure and internal linking — so Google understands your content and ranks it higher. My On-Page SEO service follows Google's E-E-A-T guidelines and targets Bangladesh-specific search patterns.",
    features: [
      "Title tag & meta description optimisation for CTR",
      "Header (H1-H3) structure with targeted keywords",
      "Keyword-optimised content following E-E-A-T guidelines",
      "Internal linking architecture for better crawlability",
      "Image alt text & schema markup implementation",
      "Content gap analysis & topical relevance improvement",
    ],
    benefits: [
      "Higher rankings for your target keywords in Bangladesh",
      "Better click-through rates with optimized meta descriptions",
      "Improved user engagement with structured content",
      "Comprehensive schema markup for rich snippets",
    ],
    process: [
      "Full page content & structure audit",
      "Keyword mapping for each page",
      "Title, meta, header optimization",
      "Internal link restructuring",
      "Schema markup implementation",
      "Performance tracking & refinement",
    ],
  },
  {
    slug: "link-building",
    icon: "🔗",
    title: "Link Building",
    subtitle: "Build Authority That Ranks",
    shortDesc: "Quality backlinks from Bangladeshi and international directories, guest posts, and niche-relevant websites that drive real authority gains.",
    desc: "Quality backlinks from Bangladeshi and international websites. I use ethical, white-hat techniques to build your site's authority and drive referral traffic. My link building strategy focuses on acquiring high-authority backlinks from Bangladesh's top business directories, news sites, and industry-relevant platforms.",
    features: [
      "Guest posting on high-authority Bangladeshi websites",
      "Local directory submissions on BD business directories",
      "Niche-relevant backlinks from industry-specific sources",
      "Broken link building for quick authority gains",
      "Competitor backlink analysis & gap identification",
      "Authority building strategy with white-hat methods",
    ],
    benefits: [
      "Boost your site's Domain Authority and search rankings",
      "Get referral traffic from high-quality Bangladeshi websites",
      "Build sustainable backlink profile with white-hat techniques",
      "Outrank competitors with superior link authority",
    ],
    process: [
      "Backlink audit & competitor analysis",
      "Prospect identification (BD & international)",
      "Outreach & relationship building",
      "Content creation for guest posts",
      "Backlink monitoring & disavow management",
    ],
  },
  {
    slug: "technical-seo",
    icon: "⚙️",
    title: "Technical SEO",
    subtitle: "Fix the Foundation. Improve Rankings.",
    shortDesc: "Site speed optimization, Core Web Vitals, mobile-first indexing, crawl budget fixes, and structured data implementation for better rankings.",
    desc: "I audit and fix technical issues holding your site back — slow speed, crawl errors, mobile issues, and Core Web Vitals — so search engines can easily find and rank your pages. Technical SEO is the foundation upon which all other SEO efforts are built.",
    features: [
      "Core Web Vitals optimisation (LCP, FID, CLS)",
      "Site speed & performance audit with actionable fixes",
      "Mobile-first indexing check & optimization",
      "Crawl budget optimisation for better indexation",
      "Structured data / Schema markup (JSON-LD)",
      "Sitemap & robots.txt management for optimal crawling",
    ],
    benefits: [
      "Faster loading pages that keep visitors engaged",
      "Better mobile experience for Bangladesh's mobile-first users",
      "Improved crawlability leading to more indexed pages",
      "Rich snippets in search results with proper schema",
    ],
    process: [
      "Comprehensive technical audit (30+ checkpoints)",
      "Core Web Vitals analysis & optimization",
      "Mobile usability fixes",
      "Crawl & indexation optimization",
      "Schema markup deployment",
      "Monthly technical monitoring",
    ],
  },
  {
    slug: "geo-ai-search",
    icon: "🤖",
    title: "GEO & AI Search",
    subtitle: "Get Found in ChatGPT, Gemini & AI Overviews",
    shortDesc: "Optimize for ChatGPT, Gemini, Perplexity, and Google AI Overviews. Entity-first SEO built for the AI-powered search era.",
    desc: "Optimise your content for the AI-powered search era. I structure your site so AI systems — Google AI Overviews, ChatGPT, Perplexity — can accurately extract and cite your business. GEO (Generative Engine Optimization) is the future of search, and I prepare your Bangladesh business for it.",
    features: [
      "Entity-first content structure for AI understanding",
      "AI-friendly FAQ/QA optimisation for featured snippets",
      "Semantic topical clustering for authority building",
      "Authority signal building for E-E-A-T compliance",
      "Featured snippet targeting & optimization",
      "Generative Engine readiness for ChatGPT & Gemini",
    ],
    benefits: [
      "Get cited in Google AI Overviews for your target queries",
      "Appear in ChatGPT and Perplexity responses",
      "Future-proof your SEO for the AI search era",
      "Build entity-based authority that lasts",
    ],
    process: [
      "AI search readiness audit",
      "Entity extraction & content restructuring",
      "FAQ & Q&A content optimization for AI extraction",
      "Topical authority cluster development",
      "E-E-A-T signal enhancement",
      "Monthly GEO performance monitoring",
    ],
  },
  {
    slug: "ecommerce-seo",
    icon: "🛒",
    title: "E-commerce SEO",
    subtitle: "Sell More With Organic Search",
    shortDesc: "Shopify, Daraz, WooCommerce SEO. Product page optimization, category restructuring, and conversion-focused search strategy.",
    desc: "From Daraz sellers to Shopify stores, I optimise product pages, category structure, and technical setup so your products rank higher and convert better. My E-commerce SEO service is tailored for Bangladeshi online retailers selling on local and international platforms.",
    features: [
      "Product page optimisation for search & conversions",
      "Category structure & siloing for better topical authority",
      "Shopify/WooCommerce/Daraz SEO best practices",
      "Review schema & rich snippets for product pages",
      "E-commerce site speed optimization",
      "Conversion-focused SEO strategy for BD e-commerce",
    ],
    benefits: [
      "Rank product pages for high-intent purchase keywords",
      "Fix crawl budget, duplicate content & faceted navigation",
      "Increase organic traffic to category & product pages",
      "Boost e-commerce conversion rate with SEO-optimized content",
    ],
    process: [
      "E-commerce site audit (technical + content)",
      "Product & category keyword mapping",
      "On-page optimization for product pages",
      "Category structure & internal linking overhaul",
      "Schema markup (Product, Review, Breadcrumb)",
      "Monthly performance reporting & optimization",
    ],
  },
];

export default services;
