const industries = [
  {
    slug: "garments-textile",
    title: "SEO for Garments & Textile in Bangladesh",
    shortTitle: "Garments & Textile",
    icon: "👕",
    desc: "Bangladesh's RMG sector is the backbone of our economy. We help garment manufacturers and textile mills dominate Google for international buyers.",
    benefits: [
      "Rank for high-value B2B keywords like 'readymade garments Bangladesh', 'textile mills in Bangladesh'",
      "Optimize for international buyer search intent (EU, US, UK markets)",
      "Generate qualified B2B inquiries through organic search",
      "Compete with Indian, Chinese, and Vietnamese exporters on Google",
    ],
    services: [
      "International SEO for RMG exporters",
      "B2B keyword research for textile industry",
      "Multi-language SEO (Bengali + English + Arabic)",
      "Supplier directory & trade platform optimization",
      "Technical SEO for factory/manufacturer websites",
    ],
  },
  {
    slug: "ecommerce",
    title: "SEO for E-commerce Stores in Bangladesh",
    shortTitle: "E-commerce",
    icon: "🛒",
    desc: "From Daraz sellers to Shopify stores — we optimize e-commerce sites to rank higher, drive traffic, and boost sales for Bangladeshi retailers.",
    benefits: [
      "Rank product pages for high-intent purchase keywords",
      "Fix crawl budget, duplicate content, and faceted navigation issues",
      "Optimize category pages to capture search traffic",
      "Increase organic conversion rate with SEO-optimized product descriptions",
    ],
    services: [
      "Daraz seller SEO optimization",
      "Shopify SEO for Bangladesh stores",
      "WooCommerce product page SEO",
      "E-commerce site structure & navigation SEO",
      "Technical SEO for online stores",
    ],
  },
  {
    slug: "smm-panel",
    title: "SEO for SMM Panel & Social Media Agencies",
    shortTitle: "SMM Panel",
    icon: "📱",
    desc: "Social media marketing panels and SMM agencies in Bangladesh need both SEO for their own site + social media optimization for clients. We deliver both.",
    benefits: [
      "Rank for 'SMM panel Bangladesh', 'social media marketing agency Dhaka'",
      "Generate leads from businesses looking for social media services",
      "Optimize service pages for local search intent",
      "Build authority in the competitive SMM space",
    ],
    services: [
      "SMM panel website SEO",
      "Local SEO for social media agencies",
      "Keyword research for social media services",
      "Competitor analysis for SMM market",
      "Content strategy for social media marketing blogs",
    ],
  },
  {
    slug: "real-estate",
    title: "SEO for Real Estate in Bangladesh",
    shortTitle: "Real Estate",
    icon: "🏢",
    desc: "Real estate developers and property agents in Bangladesh need local visibility. Rankings for apartments and plots in Dhaka and beyond.",
    benefits: [
      "Rank for location-based keywords ('flat in Banani', 'land in Uttara')",
      "Generate qualified buyer inquiries through organic search",
      "Optimize Google Business Profile for property listings",
      "Dominate local search in Dhaka, Chittagong, Sylhet",
    ],
    services: [
      "Local SEO for real estate developers",
      "Google Business Profile optimization for property agents",
      "Location page optimization for housing projects",
      "Property listing SEO & structured data",
      "Multi-location SEO for branch offices",
    ],
  },
  {
    slug: "cleaning",
    title: "SEO for Cleaning Services in Bangladesh",
    shortTitle: "Cleaning Services",
    icon: "🧹",
    desc: "Cleaning companies in Bangladesh need local customers looking for office cleaning, home deep cleaning, and industrial services. We make you found.",
    benefits: [
      "Rank for 'office cleaning service Dhaka', 'home deep cleaning Bangladesh'",
      "Dominate Google Maps for cleaning service keywords",
      "Generate calls and quote requests from organic traffic",
      "Compete with both local and international cleaning brands",
    ],
    services: [
      "Local SEO for cleaning companies",
      "Google Maps ranking for cleaning services",
      "Service page optimization for cleaning categories",
      "Review generation & reputation management",
      "Local citation building on Bangladeshi directories",
    ],
  },
  {
    slug: "spa-salon",
    title: "SEO for Spa, Salon & Beauty in Bangladesh",
    shortTitle: "Spa & Salon",
    icon: "💆",
    desc: "Spas, salons, and beauty parlours in Dhaka rely on local search to get customers. We optimize your online presence to bring more foot traffic.",
    benefits: [
      "Rank for 'spa in Gulshan', 'beauty parlour in Dhanmondi', 'salon near me'",
      "Dominate Google Maps for beauty & wellness keywords",
      "Get more booking inquiries through organic search",
      "Stand out from hundreds of local competitors",
    ],
    services: [
      "Local SEO for spas & salons",
      "Google Business Profile optimization",
      "Near-me SEO strategy for beauty services",
      "Service page optimization with pricing & booking",
      "Online review management for beauty businesses",
    ],
  },
  {
    slug: "medical",
    title: "SEO for Medical & Healthcare in Bangladesh",
    shortTitle: "Medical & Healthcare",
    icon: "🏥",
    desc: "Hospitals, clinics, and diagnostic centers in Bangladesh need patients searching for healthcare. We help you rank as the trusted medical choice.",
    benefits: [
      "Rank for 'best hospital in Dhaka', 'diagnostic center near me'",
      "Generate patient inquiries through organic healthcare search",
      "Optimize for E-E-A-T — Google's trust signal for medical content",
      "Dominate local healthcare search in your area",
    ],
    services: [
      "Local SEO for hospitals & clinics",
      "E-E-A-T optimization for medical websites",
      "Doctor profile & department page SEO",
      "Google Maps optimization for healthcare",
      "Medical content strategy with authoritative citations",
    ],
  },
  {
    slug: "education",
    title: "SEO for Education & Training in Bangladesh",
    shortTitle: "Education",
    icon: "🎓",
    desc: "Universities, coaching centers, and training institutes in Bangladesh need students searching for educational programs. We get you found.",
    benefits: [
      "Rank for admission-related keywords ('best university in Bangladesh', 'IELTS coaching Dhaka')",
      "Generate student inquiries through organic search",
      "Optimize for course and program discovery",
      "Compete in the growing EdTech space",
    ],
    services: [
      "SEO for educational institutions",
      "Course & program page optimization",
      "Local SEO for coaching centers",
      "Student inquiry generation through content SEO",
      "Google Business Profile for educational services",
    ],
  },
  {
    slug: "food-restaurant",
    title: "SEO for Restaurants & Food in Bangladesh",
    shortTitle: "Food & Restaurant",
    icon: "🍽️",
    desc: "Restaurants, cafes, and food delivery in Dhaka need hungry customers searching for places to eat. We optimize your online presence to bring more diners.",
    benefits: [
      "Rank for 'best restaurant in Gulshan', 'cafe near me', 'restaurant in Dhanmondi'",
      "Dominate Google Maps for food & dining keywords",
      "Get more calls, orders, and reservations from Google",
      "Stand out with optimized menu & service pages",
    ],
    services: [
      "Local SEO for restaurants & cafes",
      "Google Business Profile optimization for food businesses",
      "Menu & service page SEO",
      "Review management for food businesses",
      "Multi-location SEO for restaurant chains",
    ],
  },
];

export default industries;
